"""Reading and patching AoE4 ``.rec`` replay files.

A replay embeds an ``AOE4_RE`` signature followed by a UTF-16 timestamp string
that identifies the game build it was recorded on.
"""

from __future__ import annotations

import gzip
import hashlib
import json
import re
from dataclasses import dataclass
from datetime import datetime
from functools import lru_cache
from pathlib import Path

SIGNATURE = b"AOE4_RE"
_GZIP_MAGIC = b"\x1f\x8b"

# A run of letters (any script) possibly containing dots, e.g. "Jun", "μ.μ.".
_LETTER_RUN = re.compile(r"[^\W\d_](?:[^\W\d_]|\.)*")

# Precomputed CLDR month-name / AM-PM tables (generated by scripts/gen_cldr.py),
# shipped so the runtime needs neither babel nor an ~800-locale scan per run.
_CLDR_JSON = Path(__file__).with_name("cldr_datetime.json")


def _strip_marker(token: str) -> str:
    return token.replace(".", "").replace(" ", "").lower()


def build_cldr_tables_via_babel() -> tuple[dict[str, str], dict[str, str]]:
    """Build month-name -> number and AM/PM-designator -> AM/PM from CLDR (babel).

    Replay timestamps are formatted in the recorder's OS locale (any language).
    Keys are stripped of dots/spaces so a locale's variants all match (e.g. Greek
    CLDR "μ.μ." vs the Windows "μμ"). Used offline by the generator script; the
    runtime loads the shipped JSON instead.
    """
    from babel import Locale
    from babel.localedata import locale_identifiers

    months: dict[str, str] = {}
    meridiem: dict[str, str] = {}
    for ident in locale_identifiers():
        try:
            loc = Locale.parse(ident)
        except Exception:  # noqa: BLE001 - skip any locale babel can't load
            continue
        for ctx in ("format", "stand-alone"):
            for width in ("wide", "abbreviated"):
                for num, name in (loc.months.get(ctx, {}).get(width, {}) or {}).items():
                    key = _strip_marker(name)
                    if len(key) >= 3:
                        months.setdefault(key, f"{num:02d}")
            for width in ("wide", "abbreviated", "narrow"):
                periods = loc.day_periods.get(ctx, {}).get(width, {}) or {}
                for period, value in periods.items():
                    if period in ("am", "pm") and value:
                        meridiem.setdefault(_strip_marker(value), period.upper())
    return months, meridiem


@lru_cache(maxsize=1)
def _cldr_tables() -> tuple[dict[str, str], dict[str, str]]:
    if _CLDR_JSON.is_file():
        data = json.loads(_CLDR_JSON.read_text(encoding="utf-8"))
        return data["months"], data["meridiem"]
    return build_cldr_tables_via_babel()  # fallback if the shipped table is absent


def _normalise(text: str) -> str:
    """Rewrite locale month names and AM/PM markers to English numbers / AM-PM."""
    months, meridiem = _cldr_tables()

    def repl(match: re.Match[str]) -> str:
        token = match.group(0)
        key = _strip_marker(token)
        if key in meridiem:
            return meridiem[key]
        if len(key) >= 3 and key in months:
            return months[key]
        return token

    return _LETTER_RUN.sub(repl, text)


def _read_replay_bytes(path: Path) -> bytes:
    """Read a replay, transparently decompressing gzip downloads (.gz).

    Sites like aoe4world serve replays gzip-compressed; the game's own files
    are raw. We detect gzip by magic number, not by extension.
    """
    raw = Path(path).read_bytes()
    if raw[:2] == _GZIP_MAGIC:
        return gzip.decompress(raw)
    return raw


# Replay timestamps appear in several locale formats. Python's %d/%m/%H accept
# both zero-padded and unpadded input, so each line below covers its width
# variants. Tried in order; first match wins (mirrors the original tool).
_FORMATS: tuple[str, ...] = (
    "%d.%m.%Y %H:%M",       # 6.12.2023 8:27  / 06.12.2023 08:27
    "%Y-%m-%d %I:%M %p",    # 2023-12-06 8:27 AM
    "%m/%d/%Y %I:%M %p",    # 12/06/2023 8:27 AM
    "%Y-%m-%d %H:%M",       # 2023-12-06 08:27
    "%Y. %m. %d. %H:%M",    # 2026. 03. 07. 23:35 (year-first dotted, e.g. Korean/Hungarian)
    "%d/%m/%Y %H:%M",       # 06/12/2023 08:27
    "%m/%d/%Y %H:%M",       # 12/06/2023 08:27
    "%Y/%m/%d %H:%M",       # 2026/2/18 22:09 (year-first slash; added after the
                            # day/month-first slash forms so those still win)
    "%d/%m/%Y %I:%M %p",    # 25/5/2025 11:02 PM (day-first 12h, e.g. Greek locale)
    # day-Month-year, after month names are normalised to numbers
    "%d-%m-%y %I:%M %p",    # 05-Jun-26 8:50 PM -> 05-06-26 8:50 PM
    "%d-%m-%Y %I:%M %p",    # 05-Jun-2026 8:50 PM
    "%d-%m-%y %H:%M",
    "%d-%m-%Y %H:%M",
)


@dataclass(frozen=True)
class ReplayStamp:
    text: str
    value: datetime


@dataclass(frozen=True)
class PlaybackReplay:
    name: str
    path: Path
    delete_after_launch: bool


def parse_timestamp_text(text: str) -> datetime:
    """Parse a replay timestamp string against the known locale formats.

    Numeric/ISO timestamps parse directly; month-name or non-English AM/PM
    timestamps parse after CLDR normalisation (only built if the direct pass
    fails, so common numeric replays pay no cost).
    """
    for fmt in _FORMATS:
        try:
            return datetime.strptime(text, fmt)
        except ValueError:
            continue

    normalised = _normalise(text)
    if normalised != text:
        for fmt in _FORMATS:
            try:
                return datetime.strptime(normalised, fmt)
            except ValueError:
                continue

    raise ValueError(f"Could not parse replay timestamp {text!r}")


def read_timestamp(path: Path) -> ReplayStamp:
    """Scan a replay for the AOE4_RE signature and parse its build timestamp."""
    data = _read_replay_bytes(path)
    idx = data.find(SIGNATURE)
    if idx < 0:
        raise ValueError("Replay signature AOE4_RE was not found.")

    start = idx + len(SIGNATURE) + 1
    chunk = data[start : start + 128]
    text = chunk.decode("utf-16-le", errors="ignore").split("\x00", 1)[0].strip()
    if not text:
        raise ValueError("Replay timestamp was not found after AOE4_RE header.")

    return ReplayStamp(text=text, value=parse_timestamp_text(text))


def read_timestamp_optional(path: Path) -> ReplayStamp | None:
    """Like :func:`read_timestamp` but returns ``None`` instead of raising when the
    replay has no signature or its timestamp can't be parsed (e.g. a Windows locale
    that formats dates in a non-Gregorian calendar). Resolution is exe-version-first,
    so a missing/unparseable timestamp only matters when the version is unknown too."""
    try:
        return read_timestamp(path)
    except ValueError:
        return None


def read_version(path: Path) -> int | None:
    """The replay-format version: a little-endian u16 at bytes 2-4.

    This equals the recording build's ``RelicCardinal.exe`` file-version build
    number, so a replay whose version matches the installed game can be played
    directly on the live install without reconstructing an old build. Returns
    None if the file is not a recognisable replay.
    """
    data = _read_replay_bytes(path)
    if len(data) < 4 or data.find(SIGNATURE) < 0:
        return None
    return data[2] | (data[3] << 8)


def copy_to_playback(
    source: Path, playback_dir: Path, version_override: int = 0
) -> PlaybackReplay:
    """Write a replay into the game's playback folder as a .rec.

    The source may be a raw replay or a gzip download; it is decompressed as
    needed. The file is named by a short content hash. When ``version_override``
    is set, the 2-byte little-endian version header is patched so an older build
    accepts the replay.
    """
    playback_dir = Path(playback_dir)
    playback_dir.mkdir(parents=True, exist_ok=True)

    data = bytearray(_read_replay_bytes(source))
    short = hashlib.sha1(bytes(data)).hexdigest()[:12]
    if version_override > 0:
        name = f"replay_{short}_v{version_override}.rec"
    else:
        name = f"replay_{short}.rec"
    target = playback_dir / name

    if version_override > 0:
        if len(data) < 4:
            raise ValueError(f"Replay file is too small to patch version header: {target}")
        data[2] = version_override & 0xFF
        data[3] = (version_override >> 8) & 0xFF

    # If the source already *is* the generated playback file, don't rewrite it and
    # never schedule it for deletion — that would delete the user's own input.
    source = Path(source)
    if target.exists() and source.resolve() == target.resolve():
        return PlaybackReplay(name=name, path=target, delete_after_launch=False)

    target.write_bytes(bytes(data))
    return PlaybackReplay(name=name, path=target, delete_after_launch=True)
